# Generated by Django 4.2.5 on 2024-01-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(blank=True, max_length=100)),
                ('lName', models.CharField(blank=True, max_length=100)),
                ('userName', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('picture', models.FileField(upload_to='')),
                ('password', models.CharField(blank=True, max_length=100)),
                ('passw', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
