# Generated by Django 4.1.13 on 2024-01-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
