# Generated by Django 4.1.13 on 2024-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0004_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(blank=True, max_length=100)),
                ('lName', models.CharField(blank=True, max_length=100)),
                ('userName', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('picture', models.FileField(blank=True, upload_to='')),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
